name: wecare_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.3.0
  firebase_auth: 4.1.4
  cloud_firestore: 4.1.0
  firebase_storage: 11.0.6
  lottie: 2.0.0
  shared_preferences: 2.0.15
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lotties/
  uses-material-design: true

